name: feast-demo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:


jobs:
  run:
    name: Feast Demo
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: true

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Feast Demo
        run: make run
